-- TODO: Create dark theme using the following ones as inspiration:
-- https://github.com/doums/darcula/blob/master/colors/darcula.vim
-- https://github.com/rezhaTanuharja/minimalistNVIM?tab=readme-ov-file
-- https://github.com/olivercederborg/poimandres.nvim
